import type { Metadata } from "next";
import "./globals.css";
import { GlobalProviders } from "@/contexts/GlobalProviders";

export const metadata: Metadata = {
  title: "Boutain",
  // description: "Generated by create next app",
  icons: "/images/BoutainBordered.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body>
        <GlobalProviders>
          {children}
        </GlobalProviders>
      </body>
    </html>
  );
}
