import type { Metadata } from "next";
import "./globals.css";
import { GlobalProviders } from "@/contexts/GlobalProviders";
import Header from "@/components/Header";
import { AuthProvider } from "@/contexts/AuthContext";

export const metadata: Metadata = {
  title: "Boutain",
  // description: "Generated by create next app",
  icons: "/images/BoutainLogoCircle.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body>
        <GlobalProviders>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </GlobalProviders>
      </body>
    </html>
  );
}
